/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfessionsRouteImport } from './routes/confessions'
import { Route as GetRouteImport } from './routes/get'
import { Route as HqRouteImport } from './routes/hq'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as MoolaRouteImport } from './routes/moola'
import { Route as MultimxRouteImport } from './routes/multimx'
import { Route as MusicRouteImport } from './routes/music'
import { Route as PollsRouteImport } from './routes/polls'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TradepostRouteImport } from './routes/tradepost'
import { Route as ApiSmsRouteImport } from './routes/api/sms'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as GamesChessRouteImport } from './routes/games.chess'
import { Route as GamesConnect4RouteImport } from './routes/games.connect4'
import { Route as GamesMoonbaseRouteImport } from './routes/games.moonbase'
import { Route as GamesSkipboRouteImport } from './routes/games.skipbo'
import { Route as GamesTictactoeRouteImport } from './routes/games.tictactoe'
import { Route as LegalKindRouteImport } from './routes/legal.$kind'
import { Route as MultimxIndexRouteImport } from './routes/multimx.index'
import { Route as MultimxIdRouteImport } from './routes/multimx.$id'
import { Route as PortalAppRouteImport } from './routes/portal.$app'
import { Route as RoomIdRouteImport } from './routes/room.$id'
import { Route as TradepostIndexRouteImport } from './routes/tradepost.index'
import { Route as TradepostSlugRouteImport } from './routes/tradepost.$slug'
import { Route as UMxitIdRouteImport } from './routes/u.$mxitId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessionsRoute = ConfessionsRouteImport.update({
  id: '/confessions',
  path: '/confessions',
  getParentRoute: () => rootRouteImport,
} as any)
const GetRoute = GetRouteImport.update({
  id: '/get',
  path: '/get',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRoute = HqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoute = MeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const MoolaRoute = MoolaRouteImport.update({
  id: '/moola',
  path: '/moola',
  getParentRoute: () => rootRouteImport,
} as any)
const MultimxRoute = MultimxRouteImport.update({
  id: '/multimx',
  path: '/multimx',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsRoute = PollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TradepostRoute = TradepostRouteImport.update({
  id: '/tradepost',
  path: '/tradepost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsRoute = ApiSmsRouteImport.update({
  id: '/api/sms',
  path: '/api/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesChessRoute = GamesChessRouteImport.update({
  id: '/games/chess',
  path: '/games/chess',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesConnect4Route = GamesConnect4RouteImport.update({
  id: '/games/connect4',
  path: '/games/connect4',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMoonbaseRoute = GamesMoonbaseRouteImport.update({
  id: '/games/moonbase',
  path: '/games/moonbase',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSkipboRoute = GamesSkipboRouteImport.update({
  id: '/games/skipbo',
  path: '/games/skipbo',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTictactoeRoute = GamesTictactoeRouteImport.update({
  id: '/games/tictactoe',
  path: '/games/tictactoe',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalKindRoute = LegalKindRouteImport.update({
  id: '/legal/$kind',
  path: '/legal/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const MultimxIndexRoute = MultimxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MultimxRoute,
} as any)
const MultimxIdRoute = MultimxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MultimxRoute,
} as any)
const PortalAppRoute = PortalAppRouteImport.update({
  id: '/portal/$app',
  path: '/portal/$app',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TradepostIndexRoute = TradepostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TradepostRoute,
} as any)
const TradepostSlugRoute = TradepostSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TradepostRoute,
} as any)
const UMxitIdRoute = UMxitIdRouteImport.update({
  id: '/u/$mxitId',
  path: '/u/$mxitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confessions': typeof ConfessionsRoute
  '/get': typeof GetRoute
  '/hq': typeof HqRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/moola': typeof MoolaRoute
  '/multimx': typeof MultimxRouteWithChildren
  '/music': typeof MusicRoute
  '/polls': typeof PollsRoute
  '/status': typeof StatusRoute
  '/tradepost': typeof TradepostRouteWithChildren
  '/api/sms': typeof ApiSmsRoute
  '/chat/$id': typeof ChatIdRoute
  '/games/chess': typeof GamesChessRoute
  '/games/connect4': typeof GamesConnect4Route
  '/games/moonbase': typeof GamesMoonbaseRoute
  '/games/skipbo': typeof GamesSkipboRoute
  '/games/tictactoe': typeof GamesTictactoeRoute
  '/legal/$kind': typeof LegalKindRoute
  '/multimx/$id': typeof MultimxIdRoute
  '/portal/$app': typeof PortalAppRoute
  '/room/$id': typeof RoomIdRoute
  '/tradepost/$slug': typeof TradepostSlugRoute
  '/u/$mxitId': typeof UMxitIdRoute
  '/multimx/': typeof MultimxIndexRoute
  '/tradepost/': typeof TradepostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confessions': typeof ConfessionsRoute
  '/get': typeof GetRoute
  '/hq': typeof HqRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/moola': typeof MoolaRoute
  '/music': typeof MusicRoute
  '/polls': typeof PollsRoute
  '/status': typeof StatusRoute
  '/api/sms': typeof ApiSmsRoute
  '/chat/$id': typeof ChatIdRoute
  '/games/chess': typeof GamesChessRoute
  '/games/connect4': typeof GamesConnect4Route
  '/games/moonbase': typeof GamesMoonbaseRoute
  '/games/skipbo': typeof GamesSkipboRoute
  '/games/tictactoe': typeof GamesTictactoeRoute
  '/legal/$kind': typeof LegalKindRoute
  '/multimx/$id': typeof MultimxIdRoute
  '/portal/$app': typeof PortalAppRoute
  '/room/$id': typeof RoomIdRoute
  '/tradepost/$slug': typeof TradepostSlugRoute
  '/u/$mxitId': typeof UMxitIdRoute
  '/multimx': typeof MultimxIndexRoute
  '/tradepost': typeof TradepostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confessions': typeof ConfessionsRoute
  '/get': typeof GetRoute
  '/hq': typeof HqRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/moola': typeof MoolaRoute
  '/multimx': typeof MultimxRouteWithChildren
  '/music': typeof MusicRoute
  '/polls': typeof PollsRoute
  '/status': typeof StatusRoute
  '/tradepost': typeof TradepostRouteWithChildren
  '/api/sms': typeof ApiSmsRoute
  '/chat/$id': typeof ChatIdRoute
  '/games/chess': typeof GamesChessRoute
  '/games/connect4': typeof GamesConnect4Route
  '/games/moonbase': typeof GamesMoonbaseRoute
  '/games/skipbo': typeof GamesSkipboRoute
  '/games/tictactoe': typeof GamesTictactoeRoute
  '/legal/$kind': typeof LegalKindRoute
  '/multimx/$id': typeof MultimxIdRoute
  '/portal/$app': typeof PortalAppRoute
  '/room/$id': typeof RoomIdRoute
  '/tradepost/$slug': typeof TradepostSlugRoute
  '/u/$mxitId': typeof UMxitIdRoute
  '/multimx/': typeof MultimxIndexRoute
  '/tradepost/': typeof TradepostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confessions'
    | '/get'
    | '/hq'
    | '/leaderboards'
    | '/login'
    | '/meet'
    | '/moola'
    | '/multimx'
    | '/music'
    | '/polls'
    | '/status'
    | '/tradepost'
    | '/api/sms'
    | '/chat/$id'
    | '/games/chess'
    | '/games/connect4'
    | '/games/moonbase'
    | '/games/skipbo'
    | '/games/tictactoe'
    | '/legal/$kind'
    | '/multimx/$id'
    | '/portal/$app'
    | '/room/$id'
    | '/tradepost/$slug'
    | '/u/$mxitId'
    | '/multimx/'
    | '/tradepost/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confessions'
    | '/get'
    | '/hq'
    | '/leaderboards'
    | '/login'
    | '/meet'
    | '/moola'
    | '/music'
    | '/polls'
    | '/status'
    | '/api/sms'
    | '/chat/$id'
    | '/games/chess'
    | '/games/connect4'
    | '/games/moonbase'
    | '/games/skipbo'
    | '/games/tictactoe'
    | '/legal/$kind'
    | '/multimx/$id'
    | '/portal/$app'
    | '/room/$id'
    | '/tradepost/$slug'
    | '/u/$mxitId'
    | '/multimx'
    | '/tradepost'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/confessions'
    | '/get'
    | '/hq'
    | '/leaderboards'
    | '/login'
    | '/meet'
    | '/moola'
    | '/multimx'
    | '/music'
    | '/polls'
    | '/status'
    | '/tradepost'
    | '/api/sms'
    | '/chat/$id'
    | '/games/chess'
    | '/games/connect4'
    | '/games/moonbase'
    | '/games/skipbo'
    | '/games/tictactoe'
    | '/legal/$kind'
    | '/multimx/$id'
    | '/portal/$app'
    | '/room/$id'
    | '/tradepost/$slug'
    | '/u/$mxitId'
    | '/multimx/'
    | '/tradepost/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfessionsRoute: typeof ConfessionsRoute
  GetRoute: typeof GetRoute
  HqRoute: typeof HqRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LoginRoute: typeof LoginRoute
  MeetRoute: typeof MeetRoute
  MoolaRoute: typeof MoolaRoute
  MultimxRoute: typeof MultimxRouteWithChildren
  MusicRoute: typeof MusicRoute
  PollsRoute: typeof PollsRoute
  StatusRoute: typeof StatusRoute
  TradepostRoute: typeof TradepostRouteWithChildren
  ApiSmsRoute: typeof ApiSmsRoute
  ChatIdRoute: typeof ChatIdRoute
  GamesChessRoute: typeof GamesChessRoute
  GamesConnect4Route: typeof GamesConnect4Route
  GamesMoonbaseRoute: typeof GamesMoonbaseRoute
  GamesSkipboRoute: typeof GamesSkipboRoute
  GamesTictactoeRoute: typeof GamesTictactoeRoute
  LegalKindRoute: typeof LegalKindRoute
  PortalAppRoute: typeof PortalAppRoute
  RoomIdRoute: typeof RoomIdRoute
  UMxitIdRoute: typeof UMxitIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confessions': {
      id: '/confessions'
      path: '/confessions'
      fullPath: '/confessions'
      preLoaderRoute: typeof ConfessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get': {
      id: '/get'
      path: '/get'
      fullPath: '/get'
      preLoaderRoute: typeof GetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet': {
      id: '/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof MeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moola': {
      id: '/moola'
      path: '/moola'
      fullPath: '/moola'
      preLoaderRoute: typeof MoolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multimx': {
      id: '/multimx'
      path: '/multimx'
      fullPath: '/multimx'
      preLoaderRoute: typeof MultimxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls': {
      id: '/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof PollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tradepost': {
      id: '/tradepost'
      path: '/tradepost'
      fullPath: '/tradepost'
      preLoaderRoute: typeof TradepostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms': {
      id: '/api/sms'
      path: '/api/sms'
      fullPath: '/api/sms'
      preLoaderRoute: typeof ApiSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/chess': {
      id: '/games/chess'
      path: '/games/chess'
      fullPath: '/games/chess'
      preLoaderRoute: typeof GamesChessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/connect4': {
      id: '/games/connect4'
      path: '/games/connect4'
      fullPath: '/games/connect4'
      preLoaderRoute: typeof GamesConnect4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/moonbase': {
      id: '/games/moonbase'
      path: '/games/moonbase'
      fullPath: '/games/moonbase'
      preLoaderRoute: typeof GamesMoonbaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/skipbo': {
      id: '/games/skipbo'
      path: '/games/skipbo'
      fullPath: '/games/skipbo'
      preLoaderRoute: typeof GamesSkipboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/tictactoe': {
      id: '/games/tictactoe'
      path: '/games/tictactoe'
      fullPath: '/games/tictactoe'
      preLoaderRoute: typeof GamesTictactoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$kind': {
      id: '/legal/$kind'
      path: '/legal/$kind'
      fullPath: '/legal/$kind'
      preLoaderRoute: typeof LegalKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multimx/': {
      id: '/multimx/'
      path: '/'
      fullPath: '/multimx/'
      preLoaderRoute: typeof MultimxIndexRouteImport
      parentRoute: typeof MultimxRoute
    }
    '/multimx/$id': {
      id: '/multimx/$id'
      path: '/$id'
      fullPath: '/multimx/$id'
      preLoaderRoute: typeof MultimxIdRouteImport
      parentRoute: typeof MultimxRoute
    }
    '/portal/$app': {
      id: '/portal/$app'
      path: '/portal/$app'
      fullPath: '/portal/$app'
      preLoaderRoute: typeof PortalAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id': {
      id: '/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tradepost/': {
      id: '/tradepost/'
      path: '/'
      fullPath: '/tradepost/'
      preLoaderRoute: typeof TradepostIndexRouteImport
      parentRoute: typeof TradepostRoute
    }
    '/tradepost/$slug': {
      id: '/tradepost/$slug'
      path: '/$slug'
      fullPath: '/tradepost/$slug'
      preLoaderRoute: typeof TradepostSlugRouteImport
      parentRoute: typeof TradepostRoute
    }
    '/u/$mxitId': {
      id: '/u/$mxitId'
      path: '/u/$mxitId'
      fullPath: '/u/$mxitId'
      preLoaderRoute: typeof UMxitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MultimxRouteChildren {
  MultimxIdRoute: typeof MultimxIdRoute
  MultimxIndexRoute: typeof MultimxIndexRoute
}

const MultimxRouteChildren: MultimxRouteChildren = {
  MultimxIdRoute: MultimxIdRoute,
  MultimxIndexRoute: MultimxIndexRoute,
}

const MultimxRouteWithChildren =
  MultimxRoute._addFileChildren(MultimxRouteChildren)

interface TradepostRouteChildren {
  TradepostSlugRoute: typeof TradepostSlugRoute
  TradepostIndexRoute: typeof TradepostIndexRoute
}

const TradepostRouteChildren: TradepostRouteChildren = {
  TradepostSlugRoute: TradepostSlugRoute,
  TradepostIndexRoute: TradepostIndexRoute,
}

const TradepostRouteWithChildren = TradepostRoute._addFileChildren(
  TradepostRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfessionsRoute: ConfessionsRoute,
  GetRoute: GetRoute,
  HqRoute: HqRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LoginRoute: LoginRoute,
  MeetRoute: MeetRoute,
  MoolaRoute: MoolaRoute,
  MultimxRoute: MultimxRouteWithChildren,
  MusicRoute: MusicRoute,
  PollsRoute: PollsRoute,
  StatusRoute: StatusRoute,
  TradepostRoute: TradepostRouteWithChildren,
  ApiSmsRoute: ApiSmsRoute,
  ChatIdRoute: ChatIdRoute,
  GamesChessRoute: GamesChessRoute,
  GamesConnect4Route: GamesConnect4Route,
  GamesMoonbaseRoute: GamesMoonbaseRoute,
  GamesSkipboRoute: GamesSkipboRoute,
  GamesTictactoeRoute: GamesTictactoeRoute,
  LegalKindRoute: LegalKindRoute,
  PortalAppRoute: PortalAppRoute,
  RoomIdRoute: RoomIdRoute,
  UMxitIdRoute: UMxitIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
